// curated database of common grocery foods with clinically accurate ratings
// for haemochromatosis patients
//
// DATA SOURCES:
// - Iron & vitamin C values: USDA FoodData Central, Foundation Foods & SR Legacy (per 100g)
// - Clinical ratings: Irish Haemochromatosis Association "Diet & Haemochromatosis" guide (Feb 2023)
//   written by Sarah Keogh, Consultant Dietitian, with INDI
// - Alcohol iron data: IHA guide table (pg 10)
//
// RATING LOGIC (based on IHA clinical guidance, NOT raw iron numbers alone):
// - "avoid"     = high heme iron (red meat, organ meat, raw shellfish), iron-fortified foods,
//                 very high total iron (>5mg/100g), or alcohol (liver stress)
// - "moderate"  = moderate heme iron (poultry, cooked fish), moderate non-heme iron,
//                 eggs, legumes, some nuts/seeds
// - "safe"      = low iron, dairy (calcium inhibits absorption), most fruits/veg,
//                 tea/coffee (tannins inhibit absorption)
//
// WHY NOT JUST USE IRON MG/100G?
// Heme iron (from animal sources) is absorbed 2-3x more efficiently than non-heme iron
// (from plants). So beef at 2.6mg/100g is MORE dangerous than spinach at 2.7mg/100g.
// The IHA guide confirms this: "Eating more foods containing non-haem iron instead of
// foods with haem iron may be helpful for people with haemochromatosis."
//
// IRON ABSORPTION ENHANCERS (flagged in reasons):
// - Vitamin C increases iron absorption — flagged when >20mg/100g
// - Alcohol increases iron absorption AND causes liver stress
// - Fructose (fruit juices) can increase absorption
//
// IRON ABSORPTION INHIBITORS (noted in reasons):
// - Calcium (dairy) reduces iron absorption
// - Tannins (tea, coffee) reduce iron absorption
// - Phytates (wholegrains, nuts, seeds, legumes) reduce iron absorption
// - Oxalates (spinach, kale, beetroot) reduce iron absorption
// - Dietary fibre reduces iron absorption
// - Eggs contain phosvitin which binds iron

const CURATED_FOODS = [

  // ═══════════════════════════════════════════════════════════════
  // RED MEAT — avoid (high heme iron, easily absorbed)
  // IHA guide: "Limit red meat. Beef, lamb and venison contain more
  // haem iron than pork or chicken."
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'cur_001',
    name: 'Beef Mince (Raw)',
    category: 'Red Meat',
    emoji: '🥩',
    iron: 2.6,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Red meat — high in heme iron which is easily absorbed. IHA advises limiting red meat.',
  },
  {
    id: 'cur_002',
    name: 'Beef Steak — Sirloin (Raw)',
    category: 'Red Meat',
    emoji: '🥩',
    iron: 2.1,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Red meat — high in heme iron. IHA guide lists 100g beef at 2.7mg iron.',
  },
  {
    id: 'cur_003',
    name: 'Beef Steak — Rump (Raw)',
    category: 'Red Meat',
    emoji: '🥩',
    iron: 2.4,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Red meat — high in heme iron which is easily absorbed.',
  },
  {
    id: 'cur_004',
    name: 'Beef Roasting Joint (Raw)',
    category: 'Red Meat',
    emoji: '🥩',
    iron: 2.3,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Red meat — high in heme iron which is easily absorbed.',
  },
  {
    id: 'cur_005',
    name: 'Beef Stewing Steak (Raw)',
    category: 'Red Meat',
    emoji: '🥩',
    iron: 2.8,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Red meat — high in heme iron which is easily absorbed.',
  },
  {
    id: 'cur_006',
    name: 'Lamb Chop (Raw)',
    category: 'Red Meat',
    emoji: '🥩',
    iron: 1.6,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Red meat — IHA specifically lists lamb as high heme iron.',
  },
  {
    id: 'cur_007',
    name: 'Lamb Leg (Raw)',
    category: 'Red Meat',
    emoji: '🥩',
    iron: 1.8,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Red meat — high in heme iron which is easily absorbed.',
  },
  {
    id: 'cur_008',
    name: 'Pork Chop (Raw)',
    category: 'Red Meat',
    emoji: '🥩',
    iron: 0.9,
    vitaminC: 0.6,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Red meat — contains heme iron. Lower than beef/lamb but still best limited.',
  },
  {
    id: 'cur_009',
    name: 'Pork Loin (Raw)',
    category: 'Red Meat',
    emoji: '🥩',
    iron: 0.7,
    vitaminC: 0.3,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Red meat — contains heme iron. IHA lists red meat as a haem iron food to limit.',
  },
  {
    id: 'cur_010',
    name: 'Bacon Rashers (Raw)',
    category: 'Red Meat',
    emoji: '🥓',
    iron: 0.7,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Processed red meat — contains heme iron.',
  },
  {
    id: 'cur_011',
    name: 'Sausages — Pork (Raw)',
    category: 'Red Meat',
    emoji: '🌭',
    iron: 1.3,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Processed red meat — contains heme iron.',
  },
  {
    id: 'cur_012',
    name: 'Beef Burger (Raw)',
    category: 'Red Meat',
    emoji: '🍔',
    iron: 2.1,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Red meat — high in heme iron which is easily absorbed.',
  },
  {
    id: 'cur_013',
    name: 'Venison (Raw)',
    category: 'Red Meat',
    emoji: '🥩',
    iron: 3.4,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Red meat — IHA specifically lists venison as high heme iron. Avoid.',
  },
  {
    id: 'cur_014',
    name: 'Ham — Cooked Sliced',
    category: 'Red Meat',
    emoji: '🥩',
    iron: 0.9,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Processed meat — contains heme iron. Limit intake.',
  },

  // ═══════════════════════════════════════════════════════════════
  // ORGAN MEAT — avoid (very high heme iron)
  // IHA guide: "Avoid liver and offal and foods such as pâté"
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'cur_015',
    name: 'Liver — Beef (Raw)',
    category: 'Organ Meat',
    emoji: '🫀',
    iron: 6.5,
    vitaminC: 1.3,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Organ meat — extremely high heme iron. IHA: "Avoid liver and offal." 100g lambs liver = 6.5mg.',
  },
  {
    id: 'cur_016',
    name: 'Liver — Chicken (Raw)',
    category: 'Organ Meat',
    emoji: '🫀',
    iron: 9.0,
    vitaminC: 17.9,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Organ meat — extremely high heme iron. Avoid completely.',
  },
  {
    id: 'cur_017',
    name: 'Chicken Liver Pâté',
    category: 'Organ Meat',
    emoji: '🫀',
    iron: 6.0,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Organ meat product — IHA: "Avoid liver and offal and foods such as pâté." 50g = 3.0mg iron.',
  },
  {
    id: 'cur_018',
    name: 'Black Pudding',
    category: 'Organ Meat',
    emoji: '🩸',
    iron: 11.8,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Made from blood — extremely high heme iron. IHA: 2 slices (60g) = 7.1mg iron. Avoid completely.',
  },
  {
    id: 'cur_019',
    name: 'White Pudding',
    category: 'Organ Meat',
    emoji: '🩸',
    iron: 4.5,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'High iron content from meat products. Common in Irish breakfast — best avoided.',
  },
  {
    id: 'cur_020',
    name: 'Kidney — Beef (Raw)',
    category: 'Organ Meat',
    emoji: '🫀',
    iron: 5.4,
    vitaminC: 9.4,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Organ meat — IHA: "Avoid liver and offal." Very high heme iron.',
  },

  // ═══════════════════════════════════════════════════════════════
  // POULTRY — moderate (lower heme iron than red meat)
  // IHA guide lists chicken and turkey as haem iron foods but
  // notes they have less than red meat
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'cur_021',
    name: 'Chicken Breast (Raw)',
    category: 'Poultry',
    emoji: '🍗',
    iron: 0.4,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Poultry — lower heme iron than red meat. IHA: 1 small fillet (120g cooked) = 0.5mg iron.',
  },
  {
    id: 'cur_022',
    name: 'Chicken Thigh (Raw)',
    category: 'Poultry',
    emoji: '🍗',
    iron: 0.8,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Dark meat — slightly more heme iron than breast. IHA: 1 chicken leg = 1.4mg iron.',
  },
  {
    id: 'cur_023',
    name: 'Chicken Drumstick (Raw)',
    category: 'Poultry',
    emoji: '🍗',
    iron: 0.7,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Poultry — contains heme iron but less than red meat. Eat in moderation.',
  },
  {
    id: 'cur_024',
    name: 'Chicken Wings (Raw)',
    category: 'Poultry',
    emoji: '🍗',
    iron: 0.6,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Poultry — lower heme iron than red meat. Eat in moderation.',
  },
  {
    id: 'cur_025',
    name: 'Whole Chicken (Raw)',
    category: 'Poultry',
    emoji: '🍗',
    iron: 0.9,
    vitaminC: 1.6,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Poultry — mixed white and dark meat. Lower heme iron than red meat.',
  },
  {
    id: 'cur_026',
    name: 'Turkey Breast (Raw)',
    category: 'Poultry',
    emoji: '🦃',
    iron: 0.5,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Poultry — IHA: 100g turkey breast = 0.6mg iron. Lower than red meat.',
  },
  {
    id: 'cur_027',
    name: 'Turkey Mince (Raw)',
    category: 'Poultry',
    emoji: '🦃',
    iron: 0.8,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Good alternative to beef mince — lower heme iron content.',
  },
  {
    id: 'cur_028',
    name: 'Duck Breast (Raw)',
    category: 'Poultry',
    emoji: '🦆',
    iron: 2.4,
    vitaminC: 3.5,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Higher heme iron than chicken — closer to red meat. Eat sparingly.',
  },

  // ═══════════════════════════════════════════════════════════════
  // FISH — mostly safe (white fish) to moderate (oily fish)
  // IHA lists fish as a haem iron food but lower risk than meat
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'cur_029',
    name: 'Salmon Fillet (Raw)',
    category: 'Fish',
    emoji: '🐟',
    iron: 0.3,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Oily fish — very low iron. IHA: 1 salmon darne (100g) = 0.4mg iron. Good protein choice.',
  },
  {
    id: 'cur_030',
    name: 'Cod Fillet (Raw)',
    category: 'Fish',
    emoji: '🐟',
    iron: 0.1,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'White fish — very low iron. Excellent protein source for HH patients.',
  },
  {
    id: 'cur_031',
    name: 'Haddock Fillet (Raw)',
    category: 'Fish',
    emoji: '🐟',
    iron: 0.2,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'White fish — very low iron. Great choice for HH patients.',
  },
  {
    id: 'cur_032',
    name: 'Tuna — Tinned in Brine',
    category: 'Fish',
    emoji: '🐟',
    iron: 1.1,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'IHA: 100g tin of tuna drained = 1.1mg iron. Moderate — limit portions.',
  },
  {
    id: 'cur_033',
    name: 'Mackerel Fillet (Raw)',
    category: 'Fish',
    emoji: '🐟',
    iron: 1.3,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Oily fish — IHA: 1 fillet of mackerel (80g) = 1.0mg iron. Moderate intake.',
  },
  {
    id: 'cur_034',
    name: 'Sardines — Tinned in Brine',
    category: 'Fish',
    emoji: '🐟',
    iron: 2.9,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'IHA: 120g can sardines drained (90g) = 2.5mg iron. Higher than other fish.',
  },
  {
    id: 'cur_035',
    name: 'Fish Fingers (Frozen)',
    category: 'Fish',
    emoji: '🐟',
    iron: 0.4,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'White fish in breadcrumb — low iron. Safe choice.',
  },
  {
    id: 'cur_036',
    name: 'Smoked Salmon',
    category: 'Fish',
    emoji: '🐟',
    iron: 0.3,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to eat.',
  },
  {
    id: 'cur_037',
    name: 'Prawns (Raw)',
    category: 'Shellfish',
    emoji: '🦐',
    iron: 0.5,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Shellfish — cook thoroughly. IHA: avoid raw shellfish due to Vibrio vulnificus risk.',
  },
  {
    id: 'cur_038',
    name: 'Mussels (Raw)',
    category: 'Shellfish',
    emoji: '🦪',
    iron: 6.7,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Very high heme iron. IHA: avoid raw shellfish — Vibrio vulnificus bacteria thrives on iron.',
  },
  {
    id: 'cur_039',
    name: 'Oysters (Raw)',
    category: 'Shellfish',
    emoji: '🦪',
    iron: 5.1,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Very high heme iron. IHA: avoid raw shellfish due to serious infection risk with iron overload.',
  },

  // ═══════════════════════════════════════════════════════════════
  // DAIRY — safe (calcium inhibits iron absorption)
  // IHA guide: "Calcium rich foods with meals... may help to
  // reduce iron absorption"
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'cur_040',
    name: 'Whole Milk',
    category: 'Dairy',
    emoji: '🥛',
    iron: 0.03,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Dairy — IHA: calcium-rich foods with meals help reduce iron absorption. Excellent choice.',
  },
  {
    id: 'cur_041',
    name: 'Semi-Skimmed Milk',
    category: 'Dairy',
    emoji: '🥛',
    iron: 0.03,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Dairy — calcium inhibits iron absorption. Drink with meals to reduce iron uptake.',
  },
  {
    id: 'cur_042',
    name: 'Cheddar Cheese',
    category: 'Dairy',
    emoji: '🧀',
    iron: 0.2,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Dairy — very low iron, high calcium which inhibits iron absorption.',
  },
  {
    id: 'cur_043',
    name: 'Mozzarella',
    category: 'Dairy',
    emoji: '🧀',
    iron: 0.2,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Dairy — very low iron, calcium inhibits absorption.',
  },
  {
    id: 'cur_044',
    name: 'Natural Yoghurt',
    category: 'Dairy',
    emoji: '🥛',
    iron: 0.1,
    vitaminC: 0.5,
    alcohol: 0,
    rating: 'safe',
    reason: 'Dairy — IHA: yoghurt with meals may help reduce iron absorption.',
  },
  {
    id: 'cur_045',
    name: 'Greek Yoghurt',
    category: 'Dairy',
    emoji: '🥛',
    iron: 0.1,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Dairy — calcium-rich, very low iron. Excellent choice.',
  },
  {
    id: 'cur_046',
    name: 'Butter',
    category: 'Dairy',
    emoji: '🧈',
    iron: 0.02,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Virtually no iron. Note: IHA says butter and cream have no calcium.',
  },
  {
    id: 'cur_047',
    name: 'Cream Cheese',
    category: 'Dairy',
    emoji: '🧀',
    iron: 0.1,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Dairy — very low iron.',
  },
  {
    id: 'cur_048',
    name: 'Cottage Cheese',
    category: 'Dairy',
    emoji: '🧀',
    iron: 0.1,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Dairy — very low iron, good protein source.',
  },
  {
    id: 'cur_049',
    name: 'Eggs — Whole (Raw)',
    category: 'Dairy',
    emoji: '🥚',
    iron: 1.8,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'IHA: 1 boiled egg = 1.0mg iron. Contains phosvitin which binds iron, reducing absorption.',
  },

  // ═══════════════════════════════════════════════════════════════
  // VEGETABLES — mostly safe (non-heme iron, often with inhibitors)
  // IHA guide: "Eat plenty of fruits, vegetables..." and notes
  // oxalates in spinach/kale actually reduce absorption
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'cur_050',
    name: 'Potatoes (Raw)',
    category: 'Vegetables',
    emoji: '🥔',
    iron: 0.8,
    vitaminC: 19.7,
    alcohol: 0,
    rating: 'safe',
    reason: 'Low non-heme iron — safe staple. IHA: eat potatoes with skin for extra fibre.',
  },
  {
    id: 'cur_051',
    name: 'Sweet Potatoes (Raw)',
    category: 'Vegetables',
    emoji: '🍠',
    iron: 0.6,
    vitaminC: 2.4,
    alcohol: 0,
    rating: 'safe',
    reason: 'Low non-heme iron — safe to eat.',
  },
  {
    id: 'cur_052',
    name: 'Carrots (Raw)',
    category: 'Vegetables',
    emoji: '🥕',
    iron: 0.3,
    vitaminC: 5.9,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — excellent choice.',
  },
  {
    id: 'cur_053',
    name: 'Broccoli (Raw)',
    category: 'Vegetables',
    emoji: '🥦',
    iron: 0.7,
    vitaminC: 89.2,
    alcohol: 0,
    rating: 'safe',
    reason: 'Non-heme iron. High vitamin C but IHA guide says whole fruit/veg vitamin C is fine — no need to avoid.',
  },
  {
    id: 'cur_054',
    name: 'Spinach (Raw)',
    category: 'Vegetables',
    emoji: '🥬',
    iron: 2.7,
    vitaminC: 28.1,
    alcohol: 0,
    rating: 'safe',
    reason: 'IHA: oxalates in spinach actually reduce iron absorption. No need to avoid despite higher iron number.',
  },
  {
    id: 'cur_055',
    name: 'Kale (Raw)',
    category: 'Vegetables',
    emoji: '🥬',
    iron: 1.5,
    vitaminC: 120.0,
    alcohol: 0,
    rating: 'safe',
    reason: 'IHA: leafy greens with meals help reduce iron absorption due to oxalates.',
  },
  {
    id: 'cur_056',
    name: 'Tomatoes (Raw)',
    category: 'Vegetables',
    emoji: '🍅',
    iron: 0.3,
    vitaminC: 13.7,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to eat.',
  },
  {
    id: 'cur_057',
    name: 'Onions (Raw)',
    category: 'Vegetables',
    emoji: '🧅',
    iron: 0.2,
    vitaminC: 7.4,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to eat.',
  },
  {
    id: 'cur_058',
    name: 'Garlic (Raw)',
    category: 'Vegetables',
    emoji: '🧄',
    iron: 1.7,
    vitaminC: 31.2,
    alcohol: 0,
    rating: 'safe',
    reason: 'Used in small amounts — negligible iron contribution per serving.',
  },
  {
    id: 'cur_059',
    name: 'Mushrooms (Raw)',
    category: 'Vegetables',
    emoji: '🍄',
    iron: 0.5,
    vitaminC: 2.1,
    alcohol: 0,
    rating: 'safe',
    reason: 'Low non-heme iron — safe to eat.',
  },
  {
    id: 'cur_060',
    name: 'Peppers — Bell (Raw)',
    category: 'Vegetables',
    emoji: '🫑',
    iron: 0.4,
    vitaminC: 127.7,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron. High vitamin C but IHA says whole fruit/veg vitamin C is generally fine.',
  },
  {
    id: 'cur_061',
    name: 'Courgette / Zucchini (Raw)',
    category: 'Vegetables',
    emoji: '🥒',
    iron: 0.4,
    vitaminC: 17.9,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to eat.',
  },
  {
    id: 'cur_062',
    name: 'Cucumber (Raw)',
    category: 'Vegetables',
    emoji: '🥒',
    iron: 0.3,
    vitaminC: 2.8,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to eat.',
  },
  {
    id: 'cur_063',
    name: 'Lettuce — Iceberg (Raw)',
    category: 'Vegetables',
    emoji: '🥬',
    iron: 0.4,
    vitaminC: 2.8,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to eat.',
  },
  {
    id: 'cur_064',
    name: 'Sweetcorn — Tinned',
    category: 'Vegetables',
    emoji: '🌽',
    iron: 0.5,
    vitaminC: 6.8,
    alcohol: 0,
    rating: 'safe',
    reason: 'Low non-heme iron — safe to eat.',
  },
  {
    id: 'cur_065',
    name: 'Peas — Frozen',
    category: 'Vegetables',
    emoji: '🫛',
    iron: 1.5,
    vitaminC: 40.0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Non-heme iron with phytates which reduce absorption. Safe to eat.',
  },
  {
    id: 'cur_066',
    name: 'Green Beans (Raw)',
    category: 'Vegetables',
    emoji: '🫘',
    iron: 1.0,
    vitaminC: 12.2,
    alcohol: 0,
    rating: 'safe',
    reason: 'Low non-heme iron — safe to eat.',
  },
  {
    id: 'cur_067',
    name: 'Cauliflower (Raw)',
    category: 'Vegetables',
    emoji: '🥦',
    iron: 0.4,
    vitaminC: 48.2,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to eat.',
  },
  {
    id: 'cur_068',
    name: 'Cabbage (Raw)',
    category: 'Vegetables',
    emoji: '🥬',
    iron: 0.5,
    vitaminC: 36.6,
    alcohol: 0,
    rating: 'safe',
    reason: 'Low non-heme iron — safe to eat. Common in Irish cooking.',
  },
  {
    id: 'cur_069',
    name: 'Beetroot (Raw)',
    category: 'Vegetables',
    emoji: '🟣',
    iron: 0.8,
    vitaminC: 4.9,
    alcohol: 0,
    rating: 'safe',
    reason: 'Contains oxalates which reduce iron absorption. Safe to eat.',
  },
  {
    id: 'cur_070',
    name: 'Parsnips (Raw)',
    category: 'Vegetables',
    emoji: '🥕',
    iron: 0.6,
    vitaminC: 17.0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Low non-heme iron — safe to eat. Common in Irish cooking.',
  },
  {
    id: 'cur_071',
    name: 'Turnip / Swede (Raw)',
    category: 'Vegetables',
    emoji: '🥕',
    iron: 0.3,
    vitaminC: 18.0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to eat. Common in Irish stews.',
  },
  {
    id: 'cur_072',
    name: 'Celery (Raw)',
    category: 'Vegetables',
    emoji: '🥬',
    iron: 0.2,
    vitaminC: 3.1,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to eat.',
  },
  {
    id: 'cur_073',
    name: 'Avocado (Raw)',
    category: 'Vegetables',
    emoji: '🥑',
    iron: 0.6,
    vitaminC: 10.0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Low non-heme iron — safe to eat.',
  },

  // ═══════════════════════════════════════════════════════════════
  // FRUITS — mostly safe
  // IHA guide: "Eat plenty of fruits" — but limit fruit juice
  // (fructose can increase iron absorption)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'cur_074',
    name: 'Apple',
    category: 'Fruit',
    emoji: '🍎',
    iron: 0.1,
    vitaminC: 4.6,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — excellent snack choice.',
  },
  {
    id: 'cur_075',
    name: 'Banana',
    category: 'Fruit',
    emoji: '🍌',
    iron: 0.3,
    vitaminC: 8.7,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — excellent snack choice.',
  },
  {
    id: 'cur_076',
    name: 'Orange',
    category: 'Fruit',
    emoji: '🍊',
    iron: 0.1,
    vitaminC: 53.2,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron. IHA: whole fruit vitamin C is fine — no need to avoid. Just don\'t take vitamin C supplements.',
  },
  {
    id: 'cur_077',
    name: 'Strawberries',
    category: 'Fruit',
    emoji: '🍓',
    iron: 0.4,
    vitaminC: 58.8,
    alcohol: 0,
    rating: 'safe',
    reason: 'Low iron — safe to eat.',
  },
  {
    id: 'cur_078',
    name: 'Blueberries',
    category: 'Fruit',
    emoji: '🫐',
    iron: 0.3,
    vitaminC: 9.7,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — excellent choice. Contains oxalates which may reduce absorption.',
  },
  {
    id: 'cur_079',
    name: 'Grapes',
    category: 'Fruit',
    emoji: '🍇',
    iron: 0.4,
    vitaminC: 3.2,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to eat.',
  },
  {
    id: 'cur_080',
    name: 'Watermelon',
    category: 'Fruit',
    emoji: '🍉',
    iron: 0.2,
    vitaminC: 8.1,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to eat.',
  },
  {
    id: 'cur_081',
    name: 'Pear',
    category: 'Fruit',
    emoji: '🍐',
    iron: 0.2,
    vitaminC: 4.3,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to eat.',
  },
  {
    id: 'cur_082',
    name: 'Kiwi',
    category: 'Fruit',
    emoji: '🥝',
    iron: 0.3,
    vitaminC: 92.7,
    alcohol: 0,
    rating: 'safe',
    reason: 'Low iron. Very high vitamin C but IHA says whole fruit is fine.',
  },
  {
    id: 'cur_083',
    name: 'Mango',
    category: 'Fruit',
    emoji: '🥭',
    iron: 0.2,
    vitaminC: 36.4,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to eat.',
  },
  {
    id: 'cur_084',
    name: 'Melon — Cantaloupe',
    category: 'Fruit',
    emoji: '🍈',
    iron: 0.2,
    vitaminC: 36.7,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to eat.',
  },
  {
    id: 'cur_085',
    name: 'Raisins / Dried Fruit',
    category: 'Fruit',
    emoji: '🍇',
    iron: 1.9,
    vitaminC: 2.3,
    alcohol: 0,
    rating: 'moderate',
    reason: 'IHA lists dried fruit (raisins) as a non-heme iron food to be aware of. Eat in small amounts.',
  },
  {
    id: 'cur_086',
    name: 'Lemon',
    category: 'Fruit',
    emoji: '🍋',
    iron: 0.6,
    vitaminC: 53.0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to use. Used in small amounts.',
  },

  // ═══════════════════════════════════════════════════════════════
  // GRAINS & CEREALS
  // IHA guide: "Limit cereals that have added iron" and recommends
  // wholegrain/high fibre options (fibre inhibits absorption)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'cur_087',
    name: 'White Bread',
    category: 'Grains',
    emoji: '🍞',
    iron: 3.6,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Often fortified with iron — IHA: "limit cereals that have added iron." Check labels.',
  },
  {
    id: 'cur_088',
    name: 'Wholemeal Bread',
    category: 'Grains',
    emoji: '🍞',
    iron: 2.5,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'IHA recommends wholegrain over white. Fibre and phytates reduce iron absorption.',
  },
  {
    id: 'cur_089',
    name: 'Soda Bread',
    category: 'Grains',
    emoji: '🍞',
    iron: 1.8,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Traditional Irish bread — non-heme iron. Moderate intake is fine.',
  },
  {
    id: 'cur_090',
    name: 'White Rice (Cooked)',
    category: 'Grains',
    emoji: '🍚',
    iron: 0.2,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe staple food.',
  },
  {
    id: 'cur_091',
    name: 'Brown Rice (Cooked)',
    category: 'Grains',
    emoji: '🍚',
    iron: 0.4,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'IHA recommends brown rice. Fibre helps reduce iron absorption.',
  },
  {
    id: 'cur_092',
    name: 'Pasta (Cooked)',
    category: 'Grains',
    emoji: '🍝',
    iron: 0.5,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Low iron when not fortified — safe to eat.',
  },
  {
    id: 'cur_093',
    name: 'Porridge Oats',
    category: 'Grains',
    emoji: '🥣',
    iron: 4.7,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'IHA recommends porridge as a high-fibre breakfast. Phytates reduce iron absorption.',
  },
  {
    id: 'cur_094',
    name: 'Cornflakes (Fortified)',
    category: 'Grains',
    emoji: '🥣',
    iron: 8.0,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'IHA: "Limit cereals that have added iron." Fortified cereals = 4.0mg per 40g serving. Choose unfortified.',
  },
  {
    id: 'cur_095',
    name: 'Weetabix (Fortified)',
    category: 'Grains',
    emoji: '🥣',
    iron: 7.4,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Iron-fortified cereal — IHA advises avoiding iron-fortified breakfast cereals.',
  },
  {
    id: 'cur_096',
    name: 'Muesli (Unfortified)',
    category: 'Grains',
    emoji: '🥣',
    iron: 3.5,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'IHA recommends muesli as a high-fibre option. Check label — choose unfortified.',
  },
  {
    id: 'cur_097',
    name: 'Flour — Plain White',
    category: 'Grains',
    emoji: '🌾',
    iron: 1.2,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Low iron when unfortified — safe for baking.',
  },

  // ═══════════════════════════════════════════════════════════════
  // LEGUMES — moderate (non-heme iron with phytates)
  // IHA guide lists beans and lentils as non-heme iron foods
  // Phytates in legumes actually reduce absorption
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'cur_098',
    name: 'Baked Beans — Tinned',
    category: 'Legumes',
    emoji: '🫘',
    iron: 1.5,
    vitaminC: 1.0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Non-heme iron with phytates that reduce absorption. Moderate intake is fine.',
  },
  {
    id: 'cur_099',
    name: 'Chickpeas — Tinned',
    category: 'Legumes',
    emoji: '🫘',
    iron: 2.9,
    vitaminC: 1.3,
    alcohol: 0,
    rating: 'moderate',
    reason: 'IHA: 400g tin of chickpeas drained = 3.5mg iron. Phytates reduce absorption.',
  },
  {
    id: 'cur_100',
    name: 'Lentils — Green (Cooked)',
    category: 'Legumes',
    emoji: '🫘',
    iron: 3.3,
    vitaminC: 1.5,
    alcohol: 0,
    rating: 'moderate',
    reason: 'IHA: 100g cooked green lentils = 3.5mg iron. Non-heme, poorly absorbed.',
  },
  {
    id: 'cur_101',
    name: 'Lentils — Red (Cooked)',
    category: 'Legumes',
    emoji: '🫘',
    iron: 2.4,
    vitaminC: 0.8,
    alcohol: 0,
    rating: 'moderate',
    reason: 'IHA: 100g cooked red lentils = 2.4mg iron. Non-heme with phytates.',
  },
  {
    id: 'cur_102',
    name: 'Kidney Beans — Tinned',
    category: 'Legumes',
    emoji: '🫘',
    iron: 2.9,
    vitaminC: 1.2,
    alcohol: 0,
    rating: 'moderate',
    reason: 'IHA: 400g tin kidney beans drained = 4.8mg iron. Non-heme with phytates.',
  },
  {
    id: 'cur_103',
    name: 'Butter Beans — Tinned',
    category: 'Legumes',
    emoji: '🫘',
    iron: 2.4,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Non-heme iron with phytates — moderate intake is fine.',
  },

  // ═══════════════════════════════════════════════════════════════
  // NUTS & SEEDS — moderate (non-heme iron with phytates)
  // IHA lists nuts and seeds as non-heme iron foods
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'cur_104',
    name: 'Almonds',
    category: 'Nuts & Seeds',
    emoji: '🥜',
    iron: 3.7,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'IHA: 50g almonds = 1.7mg iron. Contains phytates and oxalates that reduce absorption.',
  },
  {
    id: 'cur_105',
    name: 'Cashews',
    category: 'Nuts & Seeds',
    emoji: '🥜',
    iron: 6.7,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'High non-heme iron per 100g — but phytates reduce absorption. Keep to small portions.',
  },
  {
    id: 'cur_106',
    name: 'Walnuts',
    category: 'Nuts & Seeds',
    emoji: '🥜',
    iron: 2.9,
    vitaminC: 1.3,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Non-heme iron with phytates — moderate in small portions.',
  },
  {
    id: 'cur_107',
    name: 'Peanuts',
    category: 'Nuts & Seeds',
    emoji: '🥜',
    iron: 4.6,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Non-heme iron with phytates — small portions are fine.',
  },
  {
    id: 'cur_108',
    name: 'Peanut Butter',
    category: 'Nuts & Seeds',
    emoji: '🥜',
    iron: 1.7,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Non-heme iron — moderate intake is fine.',
  },
  {
    id: 'cur_109',
    name: 'Pumpkin Seeds',
    category: 'Nuts & Seeds',
    emoji: '🌰',
    iron: 8.8,
    vitaminC: 1.9,
    alcohol: 0,
    rating: 'moderate',
    reason: 'IHA: 1 tbsp pumpkin seeds = 1.2mg iron. High per 100g but eaten in small portions. Phytates reduce absorption.',
  },
  {
    id: 'cur_110',
    name: 'Sunflower Seeds',
    category: 'Nuts & Seeds',
    emoji: '🌰',
    iron: 5.3,
    vitaminC: 1.4,
    alcohol: 0,
    rating: 'moderate',
    reason: 'High non-heme iron per 100g — eat in small portions only.',
  },

  // ═══════════════════════════════════════════════════════════════
  // DRINKS
  // IHA guide: tea and coffee with meals reduce iron absorption
  // Alcohol should be limited (liver stress + increases absorption)
  // Fruit juice: limit to 150ml/day, have 1hr before/after meals
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'cur_111',
    name: 'Tea — Black',
    category: 'Drinks',
    emoji: '☕',
    iron: 0,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'IHA: "Drinking tea or coffee with or just after meals may help reduce iron absorption." Actively beneficial.',
  },
  {
    id: 'cur_112',
    name: 'Coffee',
    category: 'Drinks',
    emoji: '☕',
    iron: 0,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'IHA: polyphenols in coffee reduce iron absorption. Drink with or just after meals.',
  },
  {
    id: 'cur_113',
    name: 'Orange Juice',
    category: 'Drinks',
    emoji: '🧃',
    iron: 0.2,
    vitaminC: 50.0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'IHA: "Limit fruit juices to 150ml per day and have them around 1 hour before or after meals." Fructose increases iron absorption.',
  },
  {
    id: 'cur_114',
    name: 'Apple Juice',
    category: 'Drinks',
    emoji: '🧃',
    iron: 0.1,
    vitaminC: 0.9,
    alcohol: 0,
    rating: 'moderate',
    reason: 'IHA: limit fruit juices to 150ml/day, have 1hr before or after meals.',
  },
  {
    id: 'cur_115',
    name: 'Red Wine (125ml)',
    category: 'Drinks',
    emoji: '🍷',
    iron: 0.5,
    vitaminC: 0,
    alcohol: 13.5,
    rating: 'avoid',
    reason: 'IHA: 125ml red wine = 1.1mg iron. Alcohol increases iron absorption AND causes liver stress.',
  },
  {
    id: 'cur_116',
    name: 'White Wine (125ml)',
    category: 'Drinks',
    emoji: '🍷',
    iron: 0.3,
    vitaminC: 0,
    alcohol: 12.0,
    rating: 'avoid',
    reason: 'IHA: 125ml white wine = 0.63mg iron. Alcohol increases iron absorption AND causes liver stress.',
  },
  {
    id: 'cur_117',
    name: 'Rosé Wine (125ml)',
    category: 'Drinks',
    emoji: '🍷',
    iron: 0.6,
    vitaminC: 0,
    alcohol: 12.0,
    rating: 'avoid',
    reason: 'IHA: 125ml rosé wine = 1.3mg iron. Highest iron of the wines.',
  },
  {
    id: 'cur_118',
    name: 'Stout (Pint)',
    category: 'Drinks',
    emoji: '🍺',
    iron: 0.2,
    vitaminC: 0,
    alcohol: 4.2,
    rating: 'avoid',
    reason: 'IHA: 1 pint stout = 1.1mg iron. Alcohol causes liver stress with iron overload.',
  },
  {
    id: 'cur_119',
    name: 'Lager (Pint)',
    category: 'Drinks',
    emoji: '🍺',
    iron: 0.01,
    vitaminC: 0,
    alcohol: 4.5,
    rating: 'avoid',
    reason: 'IHA: 1 pint lager = 0.01mg iron. Very low iron but alcohol still causes liver stress.',
  },
  {
    id: 'cur_120',
    name: 'Cider (500ml Bottle)',
    category: 'Drinks',
    emoji: '🍺',
    iron: 0.5,
    vitaminC: 0,
    alcohol: 4.5,
    rating: 'avoid',
    reason: 'IHA: 500ml bottle cider = 2.5mg iron. Highest iron of alcoholic drinks. Avoid.',
  },
  {
    id: 'cur_121',
    name: 'Spirits (Vodka / Whiskey)',
    category: 'Drinks',
    emoji: '🥃',
    iron: 0,
    vitaminC: 0,
    alcohol: 40.0,
    rating: 'avoid',
    reason: 'IHA: spirits = 0mg iron but alcohol still causes liver stress with haemochromatosis.',
  },

  // ═══════════════════════════════════════════════════════════════
  // SNACKS & SWEETS
  // IHA guide: "Avoid sugary foods — added sugar increases iron
  // absorption." Dark chocolate is a non-heme iron source.
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'cur_122',
    name: 'Dark Chocolate (70%+)',
    category: 'Snacks',
    emoji: '🍫',
    iron: 11.9,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'IHA lists dark chocolate and cocoa powder as non-heme iron foods. Very high iron — avoid.',
  },
  {
    id: 'cur_123',
    name: 'Milk Chocolate',
    category: 'Snacks',
    emoji: '🍫',
    iron: 2.4,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Moderate non-heme iron — small amounts are fine. Less iron than dark chocolate.',
  },
  {
    id: 'cur_124',
    name: 'Crisps — Potato',
    category: 'Snacks',
    emoji: '🥔',
    iron: 0.5,
    vitaminC: 8.0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Low iron — safe to eat.',
  },
  {
    id: 'cur_125',
    name: 'Biscuits — Digestive',
    category: 'Snacks',
    emoji: '🍪',
    iron: 2.0,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Moderate non-heme iron from flour — moderate intake is fine.',
  },
  {
    id: 'cur_126',
    name: 'Ice Cream — Vanilla',
    category: 'Snacks',
    emoji: '🍦',
    iron: 0.1,
    vitaminC: 0.6,
    alcohol: 0,
    rating: 'safe',
    reason: 'Dairy-based — very low iron. Safe to eat.',
  },

  // ═══════════════════════════════════════════════════════════════
  // CONDIMENTS & EXTRAS
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'cur_127',
    name: 'Tomato Ketchup',
    category: 'Condiments',
    emoji: '🍅',
    iron: 0.3,
    vitaminC: 4.0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe in normal amounts.',
  },
  {
    id: 'cur_128',
    name: 'Honey',
    category: 'Condiments',
    emoji: '🍯',
    iron: 0.4,
    vitaminC: 0.5,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to eat.',
  },
  {
    id: 'cur_129',
    name: 'Olive Oil',
    category: 'Condiments',
    emoji: '🫒',
    iron: 0.6,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to use.',
  },
  {
    id: 'cur_130',
    name: 'Marmite / Yeast Extract',
    category: 'Condiments',
    emoji: '🫙',
    iron: 13.0,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Extremely high iron per 100g — avoid.',
  },
  {
    id: 'cur_131',
    name: 'Soy Sauce',
    category: 'Condiments',
    emoji: '🫙',
    iron: 1.3,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Used in very small amounts — negligible iron per serving.',
  },
  {
    id: 'cur_132',
    name: 'Mayonnaise',
    category: 'Condiments',
    emoji: '🥫',
    iron: 0.3,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Very low iron — safe to use.',
  },
  {
    id: 'cur_133',
    name: 'Blackstrap Molasses',
    category: 'Condiments',
    emoji: '🫙',
    iron: 4.7,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Very high iron — UVA Health guidelines specifically advise avoiding molasses.',
  },

  // ═══════════════════════════════════════════════════════════════
  // COMMON MEALS & IRISH FOODS
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'cur_134',
    name: 'Colcannon',
    category: 'Irish',
    emoji: '🥔',
    iron: 0.6,
    vitaminC: 15.0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Potato and cabbage dish — low non-heme iron with dairy (calcium). Safe to eat.',
  },
  {
    id: 'cur_135',
    name: 'Boxty',
    category: 'Irish',
    emoji: '🥔',
    iron: 0.5,
    vitaminC: 10.0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Irish potato pancake — low iron. Safe to eat.',
  },
  {
    id: 'cur_136',
    name: 'Coddle — Dublin',
    category: 'Irish',
    emoji: '🍲',
    iron: 1.0,
    vitaminC: 8.0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Contains sausages and bacon (heme iron) — eat in moderation.',
  },
  {
    id: 'cur_137',
    name: 'Irish Stew (Lamb)',
    category: 'Irish',
    emoji: '🍲',
    iron: 1.5,
    vitaminC: 6.0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Contains lamb (red meat) — high in heme iron.',
  },
  {
    id: 'cur_138',
    name: 'Shepherd\'s Pie',
    category: 'Irish',
    emoji: '🥧',
    iron: 1.8,
    vitaminC: 6.0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Contains red meat mince — high in heme iron.',
  },
  {
    id: 'cur_139',
    name: 'Fish and Chips',
    category: 'Irish',
    emoji: '🐟',
    iron: 0.5,
    vitaminC: 4.0,
    alcohol: 0,
    rating: 'safe',
    reason: 'White fish in batter with chips — low iron. Good choice when eating out.',
  },
  {
    id: 'cur_140',
    name: 'Full Irish Breakfast',
    category: 'Irish',
    emoji: '🍳',
    iron: 5.0,
    vitaminC: 0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Contains bacon, sausages, black/white pudding — very high combined heme iron. Consider eggs, toast, and beans instead.',
  },
  {
    id: 'cur_141',
    name: 'Cheese Pizza',
    category: 'Meals',
    emoji: '🍕',
    iron: 1.4,
    vitaminC: 1.0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Mostly dough and cheese — low iron. Dairy calcium helps reduce absorption.',
  },
  {
    id: 'cur_142',
    name: 'Chicken Curry',
    category: 'Meals',
    emoji: '🍛',
    iron: 0.8,
    vitaminC: 3.0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Poultry-based — moderate heme iron. Better than red meat curries.',
  },
  {
    id: 'cur_143',
    name: 'Vegetable Soup',
    category: 'Meals',
    emoji: '🍲',
    iron: 0.4,
    vitaminC: 5.0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Plant-based — low non-heme iron. Safe choice.',
  },
  {
    id: 'cur_144',
    name: 'Vegetable Stir Fry',
    category: 'Meals',
    emoji: '🥘',
    iron: 0.6,
    vitaminC: 20.0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Plant-based — low non-heme iron. Excellent choice.',
  },
  {
    id: 'cur_145',
    name: 'Cheese Toastie',
    category: 'Meals',
    emoji: '🥪',
    iron: 1.0,
    vitaminC: 0,
    alcohol: 0,
    rating: 'safe',
    reason: 'Bread and cheese — low iron. Dairy calcium helps.',
  },
  {
    id: 'cur_146',
    name: 'Spaghetti Bolognese',
    category: 'Meals',
    emoji: '🍝',
    iron: 1.8,
    vitaminC: 5.0,
    alcohol: 0,
    rating: 'avoid',
    reason: 'Contains beef mince — high heme iron. Try turkey mince as an alternative.',
  },
  {
    id: 'cur_147',
    name: 'Chicken Sandwich',
    category: 'Meals',
    emoji: '🥪',
    iron: 0.6,
    vitaminC: 2.0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Poultry — moderate heme iron. Better than ham or beef sandwiches.',
  },
  {
    id: 'cur_148',
    name: 'Tuna Mayo Sandwich',
    category: 'Meals',
    emoji: '🥪',
    iron: 0.8,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Fish-based — moderate iron. Fine in moderation.',
  },
  {
    id: 'cur_149',
    name: 'Beans on Toast',
    category: 'Meals',
    emoji: '🫘',
    iron: 1.8,
    vitaminC: 1.0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Non-heme iron from beans and bread. Phytates reduce absorption. Moderate choice.',
  },
  {
    id: 'cur_150',
    name: 'Scrambled Eggs on Toast',
    category: 'Meals',
    emoji: '🍳',
    iron: 1.4,
    vitaminC: 0,
    alcohol: 0,
    rating: 'moderate',
    reason: 'Eggs contain phosvitin which binds iron. Better breakfast choice than a fry-up.',
  },
]

export default CURATED_FOODS
