export const FOODS = [
    {name:'Porridge / oats (unfortified)',mg:'1.8mg per 40g',cat:'go',note:'Phytates reduce absorption — good for all ages'},
    {name:'Brown rice',mg:'0.4mg per 100g',cat:'go',note:'Low iron, high fibre'},
    {name:'Wholegrain bread',mg:'1.0mg per 2 slices',cat:'go',note:'Fibre inhibits absorption'},
    {name:'Eggs',mg:'1.0mg each',cat:'go',note:'Versatile non-haem protein source'},
    {name:'Beans and lentils',mg:'3.5mg per 100g',cat:'go',note:'Phytates reduce absorption significantly'},
    {name:'Spinach and kale',mg:'2.7mg per 100g',cat:'go',note:'Oxalates block iron absorption'},
    {name:'Nuts and seeds',mg:'1.2–1.7mg per 30g',cat:'go',note:'Phytates reduce absorption'},
    {name:'Milk and yoghurt',mg:'Trace',cat:'go',note:'Calcium inhibits iron absorption — ideal for children'},
    {name:'Chicken breast',mg:'0.5mg per 120g',cat:'go',note:'Low iron poultry'},
    {name:'Turkey breast',mg:'0.6mg per 100g',cat:'go',note:'Low iron poultry'},
    {name:'Salmon',mg:'0.4mg per 100g',cat:'go',note:'Low iron, high omega-3'},
    {name:'Mackerel',mg:'1.0mg per 80g',cat:'go',note:'Enjoy 1–2x per week'},
    {name:'Tuna (tinned)',mg:'1.1mg per 100g',cat:'go',note:'Enjoy regularly'},
    {name:'Cod and white fish',mg:'0.2mg per 100g',cat:'go',note:'Very low iron protein source'},
    {name:'Broccoli',mg:'0.7mg per 100g',cat:'go',note:'Low iron, high fibre'},
    {name:'Cheese',mg:'Trace',cat:'go',note:'Good calcium source — inhibits iron absorption'},
    {name:'Beef (100g serving)',mg:'2.7mg',cat:'caution',note:'Limit to 1–2x per week for adults'},
    {name:'Lamb',mg:'2.0–2.5mg per 100g',cat:'caution',note:'Limit to 1x per week'},
    {name:'Sardines',mg:'2.5mg per 90g',cat:'caution',note:'Limit portions'},
    {name:'Dark chocolate',mg:'3.0mg per 50g',cat:'caution',note:'Occasional treat only'},
    {name:'Dried fruit',mg:'1.0–2.0mg per 30g',cat:'caution',note:'Limit portions'},
    {name:'Iron-fortified breakfast cereals',mg:'4.0mg per 40g',cat:'caution',note:'Choose unfortified alternatives where possible'},
    {name:'Fruit juice',mg:'—',cat:'caution',note:'Max 150ml per day — fructose increases iron absorption'},
    {name:'Pork',mg:'1.0–1.5mg per 100g',cat:'caution',note:'Lower haem iron than beef — limit frequency'},
    {name:"Calf's liver",mg:'12.2mg per 100g',cat:'avoid',note:'Extremely high haem iron — all ages'},
    {name:'Black pudding',mg:'7.1mg per 60g',cat:'avoid',note:'Very high haem iron — all ages'},
    {name:"Lamb's liver",mg:'6.5mg per 85g',cat:'avoid',note:'Very high haem iron — all ages'},
    {name:'Chicken liver pâté',mg:'3.0mg per 50g',cat:'avoid',note:'High haem iron'},
    {name:'Raw shellfish',mg:'Variable',cat:'avoid',note:'Bacterial infection risk for HH patients — all ages'},
    {name:'Iron supplements',mg:'—',cat:'avoid',note:'Never take without medical supervision'},
    {name:'High-dose vitamin C supplements',mg:'—',cat:'avoid',note:'Dramatically increases iron absorption'},
    {name:'Cider (500ml)',mg:'2.5mg',cat:'avoid',note:'High iron content plus absorption-enhancing effect'},
  ];

export const MEALS ={
    male:[
      {time:'Breakfast',name:'Porridge with berries and black tea',desc:'Unfortified oats with blueberries and pumpkin seeds. Black tea taken with breakfast reduces iron absorption. Avoid iron-fortified cereals.',pills:['tea with meal','unfortified oats','avoid fortified cereals']},
      {time:'Mid-morning',name:'Wholegrain toast with peanut butter',desc:'Two slices of wholegrain toast with natural peanut butter. The phytates in both naturally inhibit iron absorption.',pills:['wholegrain','phytates reduce absorption']},
      {time:'Lunch',name:'Lentil and vegetable soup with wholegrain roll and milk',desc:'Red lentil soup with carrots, celery, and spinach. A glass of milk alongside — calcium reduces iron absorption.',pills:['non-haem iron','calcium with meal','high fibre']},
      {time:'Afternoon snack',name:'Natural yoghurt with apple',desc:'Yoghurt provides calcium which inhibits iron absorption and is a good protein source without significant iron content.',pills:['calcium','low iron snack']},
      {time:'Dinner',name:'Baked salmon with brown rice and roasted vegetables',desc:'Salmon fillet with brown rice, broccoli, courgette, and cherry tomatoes. Follow with a cup of tea 20–30 minutes after. Limit red meat to a maximum of 1–2 times per week.',pills:['low iron fish','wholegrain rice','tea after meal']},
      {time:'Evening',name:'Cup of tea',desc:'A final cup of black tea in the evening. If you had any iron-rich foods at dinner, tea within an hour will help further reduce iron absorption overnight.',pills:['polyphenols','inhibits absorption']},
    ],
    'female-pre':[
      {time:'Breakfast',name:'Unfortified muesli with calcium-fortified soya milk and berries',desc:'Calcium in the soya milk reduces iron absorption. Pre-menopausal women have a higher target of 16mg due to monthly iron loss through menstruation.',pills:['calcium-fortified soya','16mg daily target','unfortified muesli']},
      {time:'Mid-morning',name:'Greek yoghurt with nuts and green tea',desc:'Full-fat Greek yoghurt with a small handful of almonds and green tea. Green tea polyphenols inhibit iron absorption.',pills:['calcium','polyphenols','phytates']},
      {time:'Lunch',name:'Chickpea and vegetable wrap',desc:'Wholegrain wrap with chickpeas, spinach, red pepper, and hummus. Non-haem iron sources with natural absorption inhibitors.',pills:['non-haem iron','wholegrain wrap','high fibre']},
      {time:'Afternoon snack',name:'Apple and a small piece of hard cheese',desc:'Calcium in the cheese and fibre in the apple both help inhibit iron absorption.',pills:['calcium','low iron snack']},
      {time:'Dinner',name:'Chicken and vegetable stir-fry with brown rice',desc:'Chicken breast stir-fried with broccoli, kale, mushrooms, and ginger, served with brown rice and followed by black tea. During heavy periods, monitor for fatigue and speak to your doctor.',pills:['low iron poultry','non-haem veg','tea with meal']},
      {time:'Note',name:'Menstrual cycle awareness',desc:'Pre-menopausal women naturally lose iron through menstruation, which delays iron overload build-up. Your target of 16mg per day reflects this.',pills:['16mg daily target','monitor levels','discuss with doctor']},
    ],
    'female-post':[
      {time:'Breakfast',name:'Porridge with flaxseeds and black tea',desc:'Unfortified porridge with a tablespoon of ground flaxseeds and black tea. Post-menopausal women lose the protection of menstrual blood loss — daily targets align with men at 11mg.',pills:['11mg daily target','tea with meal','unfortified oats']},
      {time:'Mid-morning',name:'Rice cakes with peanut butter and coffee',desc:'Two plain rice cakes with natural peanut butter and a cup of coffee. Polyphenols in coffee reduce iron absorption in the same way as tea.',pills:['low iron snack','coffee inhibits iron','phytates']},
      {time:'Lunch',name:'Vegetable and bean soup with wholegrain bread and milk',desc:'Butter beans and kale soup with wholegrain bread and a glass of calcium-fortified milk. Post-menopausal women benefit most from regular calcium intake for both iron inhibition and bone health.',pills:['non-haem iron','calcium with meal','bone health']},
      {time:'Afternoon snack',name:'Handful of walnuts and green tea',desc:'Green tea polyphenols inhibit iron absorption. Walnuts provide healthy omega-3 fats and phytates.',pills:['polyphenols','phytates','healthy fats']},
      {time:'Dinner',name:'Baked cod with roasted vegetables and wholegrain pasta',desc:'Cod is very low in iron. Spinach oxalates further reduce iron absorption. Follow with tea.',pills:['very low iron fish','oxalates in spinach','tea after meal']},
      {time:'Note',name:'Post-menopause dietary changes',desc:'After menopause, iron builds up more quickly. The same dietary diligence as men is now required. Focus on limiting haem iron and including daily inhibitors.',pills:['same as male targets','increased diligence','discuss with doctor']},
    ],
    under18:[
      {time:'Important',name:'Always consult a paediatric dietitian first',desc:'Children and teenagers with haemochromatosis have higher iron needs for growth and development than adults. Any dietary changes for under 18s should be made in consultation with a paediatric dietitian and the child\'s medical team.',pills:['paediatric dietitian required','individual advice essential']},
      {time:'Breakfast',name:'Unfortified porridge with banana and a glass of milk',desc:'Never give iron-fortified cereals to children with HH without dietitian guidance. The calcium in the milk inhibits iron absorption.',pills:['avoid fortified cereals','calcium with meal','unfortified oats']},
      {time:'Mid-morning',name:'Wholegrain crackers with cheese and an apple',desc:'Cheese provides calcium which inhibits iron absorption. Whole fruit provides fibre and vitamin C without the fructose load of juice.',pills:['calcium','whole fruit','wholegrain']},
      {time:'Lunch',name:'Chicken sandwich on wholegrain bread with a glass of milk',desc:'Chicken is a low-iron protein source and a much better choice than red meat for children with HH. Milk at lunchtime adds calcium and reduces iron absorption.',pills:['low iron poultry','calcium with meal','wholegrain bread']},
      {time:'Afternoon snack',name:'Natural yoghurt with berries',desc:'Yoghurt provides calcium and protein. Berries provide natural vitamin C and fibre without the iron-absorption-enhancing effect of juice.',pills:['calcium','low iron snack','avoid fruit juice']},
      {time:'Dinner',name:'Baked salmon or cod with vegetables and rice',desc:'Fish is an excellent low-iron protein source for children. Avoid offal dishes entirely — liver, kidney, and black pudding should never be given to children with HH.',pills:['low iron fish','avoid offal','varied vegetables']},
      {time:'Note',name:'Always avoid for children with HH',desc:'Liver, black pudding, kidney, and chicken liver pâté are extremely high in haem iron and should be avoided entirely. Iron-containing vitamins or supplements should never be given without medical supervision.',pills:['no liver or offal','no iron supplements','limit fruit juice']},
    ],
  }

export const SEX_STATS = {
    male: { daily: '11mg', haem: '2–3× per week', focus: 'Limit red meat and offal' },
    'female-pre': { daily: '16mg', haem: '3–4× per week', focus: 'Balance haem and non-haem' },
    'female-post': { daily: '11mg', haem: '2–3× per week', focus: 'Same as male targets now' },
  };
